(in-package :cl-alpha-vantage-api)

;; Core Stock APIs
(defendpoint time-series-intraday)
(defendpoint time-series-daily)
(defendpoint time-series-daily-adjusted)
(defendpoint time-series-weekly)
(defendpoint time-series-weekly-adjusted)
(defendpoint time-series-monthly)
(defendpoint time-series-monthly-adjusted)
(defendpoint global-quote)
(defendpoint symbol-search)
(defendpoint market-status)

;; Fundamental Data
(defendpoint overview)
(defendpoint income-statement)
(defendpoint balance-sheet)
(defendpoint cash-flow)
(defendpoint earnings)
(defendpoint listing-status)
(defendpoint earnings-calendar)
(defendpoint ipo-calendar)

;; Forex (FX)
(defendpoint currency-exchange-rate)
(defendpoint fx-intraday)
(defendpoint fx-daily)
(defendpoint fx-weekly)
(defendpoint fx-monthly)

;; Cryptocurrencies
(defendpoint crypto-intraday)
(defendpoint digital-currency-daily)
(defendpoint digital-currency-weekly)
(defendpoint digital-currency-monthly)

;; Commodities
(defendpoint wti)
(defendpoint brent)
(defendpoint natural-gas)
(defendpoint copper)
(defendpoint aluminum)
(defendpoint wheat)
(defendpoint corn)
(defendpoint cotton)
(defendpoint sugar)
(defendpoint coffee)
(defendpoint all-commodities)

;; Economic Indicators
(defendpoint real-gdp)
(defendpoint real-gdp-per-capita)
(defendpoint treasury-yield)
(defendpoint federal-funds-rate)
(defendpoint cpi)
(defendpoint inflation)
(defendpoint retail-sales)
(defendpoint durables)
(defendpoint unemployment)
(defendpoint nonfarm-payroll)

;; Technical Indicators
(defendpoint sma)
(defendpoint ema)
(defendpoint wma)
(defendpoint dema)
(defendpoint tema)
(defendpoint trima)
(defendpoint kama)
(defendpoint mama)
(defendpoint vwap)
(defendpoint t3)
(defendpoint macd)
(defendpoint macdext)
(defendpoint stoch)
(defendpoint stochf)
(defendpoint rsi)
(defendpoint stochrsi)
(defendpoint willr)
(defendpoint adx)
(defendpoint adxr)
(defendpoint apo)
(defendpoint ppo)
(defendpoint mom)
(defendpoint bop)
(defendpoint cci)
(defendpoint cmo)
(defendpoint roc)
(defendpoint rocr)
(defendpoint aroon)
(defendpoint aroonosc)
(defendpoint mfi)
(defendpoint trix)
(defendpoint ultosc)
(defendpoint dx)
(defendpoint minus-di)
(defendpoint plus-di)
(defendpoint minus-dm)
(defendpoint plus-dm)
(defendpoint bbands)
(defendpoint midpoint)
(defendpoint midprice)
(defendpoint sar)
(defendpoint trange)
(defendpoint atr)
(defendpoint natr)
(defendpoint ad)
(defendpoint adosc)
(defendpoint obv)
(defendpoint ht-trendline)
(defendpoint ht-sine)
(defendpoint ht-trendmode)
(defendpoint ht-dcperiod)
(defendpoint ht-dcphase)
(defendpoint ht-phasor)

(defstruct end-point
  name group)

(dolist (end-point +end-points+)
  (let ((name (caar end-point))
        (group (cadar end-point)))
    (pushnew (make-end-point :name name :group group) *end-point-table*)))

;; create aliases for digital currency functions consistent with fx and core stock api
(setf (fdefinition 'crypto-daily) #'digital-currency-daily)
(setf (fdefinition 'crypto-weekly) #'digital-currency-weekly)
(setf (fdefinition 'crypto-monthly) #'digital-currency-monthly)
