(in-package :cl-alpha-vantage-api)

(defclass overview ()
  ((ticker :accessor ticker-of :initform nil)
   (asset-type :accessor asset-type-of :initform nil)
   (name :accessor name-of :initform nil)
   (description :accessor description-of :initform nil)
   (cik :accessor cik-of :initform 0)
   (exchange :accessor exchange-of :initform nil)
   (currency :accessor currency-of :initform nil)
   (country :accessor country-of :initform nil)
   (sector :accessor sector-of :initform nil)
   (industry :accessor industry-of :initform nil)
   (address :accessor address-of :initform nil)
   (fiscal-year-end :accessor fiscal-year-end-of :initform nil)
   (latest-quarter :accessor latest-quarter-of :initform (local-time:universal-to-timestamp 0))
   (market-capitalization :accessor market-capitalization-of :initform 0)
   (ebitda :accessor ebitda-of :initform 0)
   (pe-ratio :accessor pe-ratio-of :initform 0.0)
   (peg-ratio :accessor peg-ratio-of :initform 0.0)
   (book-value :accessor book-value-of :initform 0.0)
   (dividend-per-share :accessor dividend-per-share-of :initform 0.0)
   (dividend-yield :accessor dividend-yield-of :initform 0.0)
   (eps :accessor eps-of :initform 0.0)
   (revenue-per-share-ttm :accessor revenue-per-share-ttm-of :initform 0.0)
   (profit-margin :accessor profit-margin-of :initform 0.0)
   (operating-margin-ttm :accessor operating-margin-ttm-of :initform 0.0)
   (return-on-assets-ttm :accessor return-on-assets-ttm-of :initform 0.0)
   (return-on-equity-ttm :accessor return-on-equity-ttm-of :initform 0.0)
   (revenue-ttm :accessor revenue-ttm-of :initform 0)
   (gross-profit-ttm :accessor gross-profit-ttm-of :initform 0)
   (diluted-eps-ttm :accessor diluted-eps-ttm-of :initform 0.0)
   (quarterly-earnings-growth-yoy :accessor quarterly-earnings-growth-yoy-of :initform 0.0)
   (quarterly-revenue-growth-yoy :accessor quarterly-revenue-growth-yoy-of :initform 0.0)
   (analyst-target-price :accessor analyst-target-price-of :initform 0.0)
   (trailing-pe :accessor trailing-pe-of :initform 0.0)
   (forward-pe :accessor forward-pe-of :initform 0.0)
   (price-to-sales-ratio-ttm :accessor price-to-sales-ratio-ttm-of :initform 0.0)
   (price-to-book-ratio :accessor price-to-book-ratio-of :initform 0.0)
   (ev-to-revenue :accessor ev-to-revenue-of :initform 0.0)
   (ev-to-ebitda :accessor ev-to-ebitda-of :initform 0.0)
   (beta :accessor beta-of :initform 0.0)
   (52-week-high :accessor 52-week-high-of :initform 0.0)
   (52-week-low :accessor 52-week-low-of :initform 0.0)
   (50-day-moving-average :accessor 50-day-moving-average-of :initform 0.0)
   (200-day-moving-average :accessor 200-day-moving-average-of :initform 0.0)
   (shares-outstanding :accessor shares-outstanding-of :initform 0)
   (dividend-date :accessor dividend-date-of :initform (local-time:universal-to-timestamp 0))
   (ex-dividend-date :accessor ex-dividend-date-of :initform (local-time:universal-to-timestamp 0))))

(defclass income-statement ()
  ((report-period :accessor report-period-of :initform nil)
   (fiscal-date-ending :accessor fiscal-date-ending-of :initform (local-time:universal-to-timestamp 0))
   (reported-currency :accessor reported-currency-of :initform nil)
   (gross-profit :accessor gross-profit-of :initform 0)
   (total-revenue :accessor total-revenue-of :initform 0)
   (cost-of-revenue :accessor cost-of-revenue-of :initform 0)
   (cost-of-goods-and-services-sold :accessor cost-of-goods-and-services-sold-of :initform 0)
   (operating-income :accessor operating-income-of :initform 0)
   (selling-general-and-administrative :accessor selling-general-and-administrative-of :initform 0)
   (research-and-development :accessor research-and-development-of :initform 0)
   (operating-expenses :accessor operating-expenses-of :initform 0)
   (investment-income-net :accessor investment-income-net-of :initform 0)
   (net-interest-income :accessor net-interest-income-of :initform 0)
   (interest-income :accessor interest-income-of :initform 0)
   (interest-expense :accessor interest-expense-of :initform 0)
   (non-interest-income :accessor non-interest-income-of :initform 0)
   (other-non-operating-income :accessor other-non-operating-income-of :initform 0)
   (depreciation :accessor depreciation-of :initform 0)
   (depreciation-and-amortization :accessor depreciation-and-amortization-of :initform 0)
   (income-before-tax :accessor income-before-tax-of :initform 0)
   (income-tax-expense :accessor income-tax-expense-of :initform 0)
   (interest-and-debt-expense :accessor interest-and-debt-expense-of :initform 0)
   (net-income-from-continuing-operations :accessor net-income-from-continuing-operations-of :initform 0)
   (comprehensive-income-net-of-tax :accessor comprehensive-income-net-of-tax-of :initform 0)
   (ebit :accessor ebit-of :initform 0)
   (ebitda :accessor ebitda-of :initform 0)
   (net-income :accessor net-income-of :initform 0)))

(defclass balance-sheet ()
  ((report-period :accessor report-period-of :initform nil)
   (fiscal-date-ending :accessor fiscal-date-ending-of :initform (local-time:universal-to-timestamp 0))
   (reported-currency :accessor reported-currency-of :initform nil)
   (total-assets :accessor total-assets-of :initform 0)
   (total-current-assets :accessor total-current-assets-of :initform 0)
   (cash-and-cash-equivalents-at-carrying-value :accessor cash-and-cash-equivalents-at-carrying-value-of :initform 0)
   (cash-and-short-term-investments :accessor cash-and-short-term-investments-of :initform 0)
   (inventory :accessor inventory-of :initform 0)
   (current-net-receivables :accessor current-net-receivables-of :initform 0)
   (total-non-current-assets :accessor total-non-current-assets-of :initform 0)
   (property-plant-equipment :accessor property-plant-equipment-of :initform 0)
   (accumulated-depreciation-amortization-ppe :accessor accumulated-depreciation-amortization-ppe-of :initform 0)
   (intangible-assets :accessor intangible-assets-of :initform 0)
   (intangible-assets-excluding-goodwill :accessor intangible-assets-excluding-goodwill-of :initform 0)
   (goodwill :accessor goodwill-of :initform 0)
   (investments :accessor investments-of :initform 0)
   (long-term-investments :accessor long-term-investments-of :initform 0)
   (short-term-investments :accessor short-term-investments-of :initform 0)
   (other-current-assets :accessor other-current-assets-of :initform 0)
   (other-non-current-assets :accessor other-non-current-assets-of :initform 0)
   (total-liabilities :accessor total-liabilities-of :initform 0)
   (total-current-liabilities :accessor total-current-liabilities-of :initform 0)
   (current-accounts-payable :accessor current-accounts-payable-of :initform 0)
   (deferred-revenue :accessor deferred-revenue-of :initform 0)
   (current-debt :accessor current-debt-of :initform 0)
   (short-term-debt :accessor short-term-debt-of :initform 0)
   (total-non-current-liabilities :accessor total-non-current-liabilities-of :initform 0)
   (capital-lease-obligations :accessor capital-lease-obligations-of :initform 0)
   (long-term-debt :accessor long-term-debt-of :initform 0)
   (current-long-term-debt :accessor current-long-term-debt-of :initform 0)
   (long-term-debt-noncurrent :accessor long-term-debt-noncurrent-of :initform 0)
   (short-long-term-debt-total :accessor short-long-term-debt-total-of :initform 0)
   (other-current-liabilities :accessor other-current-liabilities-of :initform 0)
   (other-non-current-liabilities :accessor other-non-current-liabilities-of :initform 0)
   (total-shareholder-equity :accessor total-shareholder-equity-of :initform 0)
   (treasury-stock :accessor treasury-stock-of :initform 0)
   (retained-earnings :accessor retained-earnings-of :initform 0)
   (common-stock :accessor common-stock-of :initform 0)
   (common-stock-shares-outstanding :accessor common-stock-shares-outstanding-of :initform 0)))

(defclass cash-flow ()
  ((report-period :accessor report-period-of :initform nil)
   (fiscal-date-ending :accessor fiscal-date-ending-of :initform (local-time:universal-to-timestamp 0))
   (reported-currency :accessor reported-currency-of :initform nil)
   (operating-cashflow :accessor operating-cashflow-of :initform 0)
   (payments-for-operating-activities :accessor payments-for-operating-activities-of :initform 0)
   (proceeds-from-operating-activities :accessor proceeds-from-operating-activities-of :initform 0)
   (change-in-operating-liabilities :accessor change-in-operating-liabilities-of :initform 0)
   (change-in-operating-assets :accessor change-in-operating-assets-of :initform 0)
   (depreciation-depletion-and-amortization :accessor depreciation-depletion-and-amortization-of :initform 0)
   (capital-expenditures :accessor capital-expenditures-of :initform 0)
   (change-in-receivables :accessor change-in-receivables-of :initform 0)
   (change-in-inventory :accessor change-in-inventory-of :initform 0)
   (profit-loss :accessor profit-loss-of :initform 0)
   (cashflow-from-investment :accessor cashflow-from-investment-of :initform 0)
   (cashflow-from-financing :accessor cashflow-from-financing-of :initform 0)
   (proceeds-from-repayments-of-short-term-debt :accessor proceeds-from-repayments-of-short-term-debt-of :initform 0)
   (payments-for-repurchase-of-common-stock :accessor payments-for-repurchase-of-common-stock-of :initform 0)
   (payments-for-repurchase-of-equity :accessor payments-for-repurchase-of-equity-of :initform 0)
   (payments-for-repurchase-of-preferred-stock :accessor payments-for-repurchase-of-preferred-stock-of :initform 0)
   (dividend-payout :accessor dividend-payout-of :initform 0)
   (dividend-payout-common-stock :accessor dividend-payout-common-stock-of :initform 0)
   (dividend-payout-preferred-stock :accessor dividend-payout-preferred-stock-of :initform 0)
   (proceeds-from-issuance-of-common-stock :accessor proceeds-from-issuance-of-common-stock-of :initform 0)
   (proceeds-from-issuance-of-long-term-debt-and-capital-securities-net :accessor proceeds-from-issuance-of-long-term-debt-and-capital-securities-net-of :initform 0)
   (proceeds-from-issuance-of-preferred-stock :accessor proceeds-from-issuance-of-preferred-stock-of :initform 0)
   (proceeds-from-repurchase-of-equity :accessor proceeds-from-repurchase-of-equity-of :initform 0)
   (proceeds-from-sale-of-treasury-stock :accessor proceeds-from-sale-of-treasury-stock-of :initform 0)
   (change-in-cash-and-cash-equivalents :accessor change-in-cash-and-cash-equivalents-of :initform 0)
   (change-in-exchange-rate :accessor change-in-exchange-rate-of :initform 0)
   (net-income :accessor net-income-of :initform 0)))

(defclass earnings ()
  ((report-period :accessor report-period-of :initform nil)
   (fiscal-date-ending :accessor fiscal-date-ending-of :initform (local-time:universal-to-timestamp 0))
   (reported-eps :accessor reported-eps-of :initform 0.0)))

(defun make-overview (hash-table)
  "Create an OVERVIEW instance from HASH-TABLE."
  (make-instance-from-hash-table overview hash-table))

(defun make-income-statement (hash-table)
  "Create an INCOME-STATEMENT instance from HASH-TABLE."
  (make-instance-from-hash-table income-statement hash-table))

(defun make-balance-sheet (hash-table)
  "Create a BALANCE-SHEET instance from HASH-TABLE."
  (make-instance-from-hash-table balance-sheet hash-table))

(defun make-cash-flow (hash-table)
  "Create a CASH-FLOW instance from HASH-TABLE."
  (make-instance-from-hash-table cash-flow hash-table))

(defun make-earnings (hash-table)
  "Create an EARNINGS instance from HASH-TABLE."
  (make-instance-from-hash-table earnings hash-table))
